name: Examples CI

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: examples
    name: Java ${{ matrix.java }}
    env:
      USERNAME: ${{ github.actor }}
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        java: [17, 21]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build and Check
        run: |
          chmod +x gradlew
          ./gradlew build --no-daemon

      - name: Run standalone simple android example
        working-directory: examples/standalone/android-simple
        run: |
          chmod +x gradlew
          ./gradlew printAnimalsnifferTasks, build --no-daemon    

      - name: Run standalone multiplatform with android example
        working-directory: examples/standalone/kotlin-multi-android-desktop-server
        run: |
          chmod +x gradlew
          ./gradlew printAnimalsnifferTasks, build --no-daemon

      - name: Run standalone multiplatform with android only example
        working-directory: examples/standalone/kotlin-multi-android-only
        run: |
          chmod +x gradlew
          ./gradlew printAnimalsnifferTasks, build --no-daemon

      - name: Run standalone pure multiplatform example
        working-directory: examples/standalone/kotlin-multi-desktop-server
        run: |
          chmod +x gradlew
          ./gradlew printAnimalsnifferTasks, build --no-daemon